[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "a_trade_calendar"
version = "2025.09.01.4"
description = "适用于A股，一款简单、纯粹的交易日历工具包"
readme = "README.md"
keywords = ["a股", "日历"]
license = { text = "BSD 2-Clause License" }

