[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "a_trade_calendar"
version = "0.0.7"
description = "一款纯粹的交易日历工具包，适用于A股"
readme = "README.md"
keywords = ["a股", "日历"]
license = { text = "BSD 2-Clause License" }

